Repository DARPA-ASKEM/Model-Representations, pull requests merged in 2023-06, with the labels that each got.

#30 Add typing for stratification etc. as a "semantic"
  petrinet/examples/sir_typed.json
  petrinet/petrinet_schema.json
Labels: integration

#35 34 missing the id name description properties
  petrinet/examples/sir.json
  petrinet/examples/sir_typed.json
  petrinet/petrinet_schema.json
Labels: bug

#45 Updated the metadata schema to v2.1
  metadata_schema.json
  petrinet/examples/sir.json
  petrinet/examples/sir_typed.json
Labels: enhancement

#46 feat(petrinet): add script for AlgebraicPetri conversion
  petrinet/scripts/julia/ASKEMPetriNets.jl
  petrinet/scripts/julia/Project.toml
  petrinet/scripts/julia/test.jl
Labels: integration
